apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eduk8s-certificate
  namespace: eduk8s
spec:
  commonName: *.workshop.frankcarta.com
  issuerRef:
    name: letsencrypt-tanzudemo
    kind: ClusterIssuer
  secretName: eduk8s-cert-secret