apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-certificate
  namespace: argocd
spec:
  commonName: argocd.tanzu.frankcarta.com
  dnsNames:
  - argocd.tanzu.frankcarta.com
  issuerRef:
    name: letsencrypt-fcarta-devops
    kind: ClusterIssuer
  secretName: argocd-cert-secret