apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  name: harbor-workspace-pvc # for some reason PipelineRun only works when name is pipeline-pvc???
  name: pipeline-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi