apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterTriggerBinding
metadata:
  name: harbor-webhook-clustertriggerbinding
  namespace: default
spec:
  params:
    - name: type
      value: $(body.type)
    - name: occur_at
      value: $(body.occur_at)
    - name: operator
      value: $(body.operator)
    - name: digest
      value: $(body.event_data.resources[0].digest)
    - name: tag
      value: $(body.event_data.resources[0].tag)
    - name: resource_url
      value: $(body.event_data.resources[0].resource_url)      
    - name: date_created
      value: $(body.event_data.repository.date_created)
    - name: name
      value: $(body.event_data.repository.name)
    - name: namespace
      value: $(body.event_data.repository.namespace)
    - name: repo_full_name
      value: $(body.event_data.repository.repo_full_name)
    - name: repo_type
      value: $(body.event_data.repository.repo_type)