apiVersion: v1
items:
- apiVersion: training.eduk8s.io/v1alpha1
  kind: TrainingPortal
  metadata:
    annotations:
      kopf.zalando.org/last-handled-configuration: |
        {"spec":{"portal":{"capacity":20,"expires":"90m","ingress":{"class":"contour","domain":"workshop.frankcarta.com","protocol":"https","secret":"eduk8s-cert-secret"},"orphaned":"5m","password":"PlatformTuesday","registration":{"type":"anonymous"},"reserved":0,"sessions":{"maximum":20},"title":"Workshop Portal"},"workshops":[{"name":"lab-container-security-01"},{"name":"lab-container-security-02"},{"name":"lab-configuration-management"},{"name":"lab-tas4ops"},{"name":"lab-k8-networking"},{"name":"lab-tekton-fundamentals"},{"name":"lab-spring-boot-k8s-probes"}]},"metadata":{"labels":{"app.kubernetes.io/instance":"eduk8s"}}}
    creationTimestamp: "2021-05-24T23:51:46Z"
    generation: 5
    labels:
      app.kubernetes.io/instance: eduk8s
    managedFields:
    - apiVersion: training.eduk8s.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
        f:spec:
          .: {}
          f:portal:
            .: {}
            f:capacity: {}
            f:expires: {}
            f:orphaned: {}
            f:password: {}
            f:registration:
              .: {}
              f:type: {}
            f:reserved: {}
            f:sessions:
              .: {}
              f:maximum: {}
            f:title: {}
          f:workshops: {}
      manager: argocd-application-controller
      operation: Update
      time: "2021-05-24T23:51:46Z"
    - apiVersion: training.eduk8s.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kopf.zalando.org/last-handled-configuration: {}
        f:status:
          .: {}
          f:eduk8s:
            .: {}
            f:clients:
              .: {}
              f:robot:
                .: {}
                f:id: {}
                f:secret: {}
            f:credentials:
              .: {}
              f:admin:
                .: {}
                f:password: {}
                f:username: {}
              f:robot:
                .: {}
                f:password: {}
                f:username: {}
            f:namespace: {}
            f:phase: {}
            f:secrets:
              .: {}
              f:ingress: {}
              f:registry: {}
            f:url: {}
      manager: kopf
      operation: Update
      time: "2021-05-24T23:51:46Z"
    - apiVersion: training.eduk8s.io/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:portal:
            f:ingress:
              .: {}
              f:class: {}
              f:domain: {}
              f:protocol: {}
              f:secret: {}
      manager: kubectl-edit
      operation: Update
      time: "2021-05-25T02:15:16Z"
    name: portal
    resourceVersion: "7436907"
    selfLink: /apis/training.eduk8s.io/v1alpha1/trainingportals/portal
    uid: 7594d825-b2e7-4ed0-ba6b-739c1bc1e927
  spec:
    portal:
      capacity: 20
      expires: 90m
      ingress:
        class: contour
        domain: workshop.frankcarta.com
        protocol: https
        secret: eduk8s-cert-secret
      orphaned: 5m
      password: PlatformTuesday
      registration:
        type: anonymous
      reserved: 0
      sessions:
        maximum: 20
      title: Workshop Portal
    workshops:
    - name: lab-container-security-01
    - name: lab-container-security-02
    - name: lab-configuration-management
    - name: lab-tas4ops
    - name: lab-k8-networking
    - name: lab-tekton-fundamentals
    - name: lab-spring-boot-k8s-probes
  status:
    eduk8s:
      clients:
        robot:
          id: 6tyQuqrpcv3O8Z1JBnKGa29jERDToNVf
          secret: H1OuvwdhFgJycWIE3qVQiDAt4sRzb207
      credentials:
        admin:
          password: dk9AVRZm7eXsliaDcEv8x2t3nQBwIoPK
          username: eduk8s
        robot:
          password: dqeilckDJyfTC0aBIUHpGt8WQ6bvMF4z
          username: robot@eduk8s
      namespace: portal-ui
      phase: Running
      secrets:
        ingress: []
        registry: []
      url: http://portal-ui.workshop.frankcarta.com
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
