apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-manifest
spec:
  params:
    - name: git_user
      type: string
    - name: git_email
      type: string
    - name: digest
      type: string
  workspaces:
    - name: source
      description: A workspace that contains the fetched git repository.
  steps:
    - name: build-manifest
      workingDir: $(workspaces.source.path)
      image: harbor.tanzu.frankcarta.com/builders/tekton-task
      script: |
        #!/usr/bin/env bash
        rm -Rf tanzu-demo-lab-aws-examples
        
        git clone https://github.com/fcarta29/tanzu-demo-lab-aws-examples.git
        
        cd tanzu-demo-lab-aws-examples
        git checkout release    

        cd spring-petclinic/deploy                    
        ytt -f templates/kustomization.yaml -f templates/values.yaml -v digest='$(params.digest)' --output-files release/overlays/demo/.

        git config --global user.name "$(params.git_user)"
        git config --global user.email "$(params.git_email)"
        git commit -am "Releasing $(params.digest)"

        git pull --rebase origin spring-petclinic-demo

        git push origin release -f
        
  
